### ISSUE TITLE
Prototype: MVP

### ISSUE THREAD

**Issue by ashes999** [deengames/dajjals-minions#1]
# Must Have
- [x] Basic top-down shooter: walk around, enemies, death
- [x] Game backstory and theme: some way to communicate some part of our culture and values
- [x] Figure out distribution
- [x] Game design: something unique that makes our game fun to play (even as boxes)
- [x] Proper window size (tweak spawning, melee range, etc. so game feels balanced)
- [x] Player can't move off the screen
- [x] "Stages" where we unlock harder (eg. huge) or new types of enemies. These can be discrete (waves) or continuous (show up after a certain amount of time) @ashes999
- [x] Sound effects
  - [x] Basic
  - [x] Fix segfault
  - ~~Better rocket shot~~
- [x] More weapons, [details are here](https://github.com/MuslimGamer/pcg-shooter/wiki/Weapon-System):
  - [x] Refactoring: Pistol as a gun class
  - [x] Shotgun
  - [x] Machine-Gun
  - [x] Rocket launcher - Unique projectile & Visual effect
  - [x] Rocket launcher - Splash damage / Explosion on contact
  - [x] Railgun
- [x] Story integration.
  - [x] Intro with the Dajjal saying "more Muslim meat for my army! I'll chase you to the ends of the galaxy!"
  - [x] Intro: helmet, showing "Looks like the hyper-drive is offline. Here they come!"
  - [x] Intro shows only on first game of the session (not after restarting)
  - [x] Next button
  - [x] Skip button
  - [x] Story pane when you win
  - [x] You Win text when you close the story pane
- [ ] UX changes
  - [ ]  Sev - Added new function to UI_manager for spawning text at designated location w/colour. Require advice on calling the ui_manager class from arbitrary files/classes
  - [ ] "HP Up" "Attack Up" "Regeneration" etc. text appears and floats up (disappers) on crew-collect
  - [ ] "Crew Lost" text appears and floats up (disappears) on crew-loss
- [x] Tutorial
  - ~~WASD + mouse images (fade out on first shot)~~
  - ~~Mouse image mentions melee~~
  - ~~First reload: highlight it~~
  - ~~First enemy~~
  - ~~First power-up (for sure spawned by first enemy)~~
  - ~~First escape pod to rescue~~
  - ~~First time hyper-drive starts charging~~
  - ~~None of these happen more than once (it's not about first-game or not)~~
  - ~~Skip button also disables all these tutorials~~
- [x] Pause
  - [x] `ESC` to pause, with image ("paused"). Click/press to unpause.
  - ~~Auto-pause if window loses focus~~
- [x] Fix bugs:
  - [x] Random death
  - [x] Don't move, you shoot from the bottom-left corner
  - [x] Die with your sword out: it doesn't die
  - [x] Spawn income doesn't reduce when you die
  - [x] Score doesn't reset when you die
  - [x] Can't manually reload with R
  - [x] Cheats are broken
  - [x] Non-weapon sounds don't work? (can't repro)
    - [x]  Bullet collision sounds working
    - [x] reload sound
    - [x] pickup collection sound
  - [x] Power-ups remain after you die
  - [x] Font doesn't work on Unix any more
  - [x] Explosions sometimes stick around
  - [x] Game over screen blacks out
  - [x] Game over screen doesn't show points
  - [ ] Game slows down a lot in some cases  - Sev
    - [ ] Slow down obseverved during player input
        - [ ] Slowdown while holding attack?
        - [x] Slowdown while holding movement?
    - [x] Added cooldown to AI target selection
    - [x] Fixed bullet bug recalculating trajectory every step. Single calc on spawn
    - [x] Multiple processing on objects possible slowdown cause - Unknown cause
        - [x] NPC add multiple crew on collection.
        - [x] 2x bullet objects detected on bullet death? - confirmed only 1 at time of spawn
  - [x] You can wrap around the left/top side of the screen but not the bottom/right  -Sev
  - [x] Bullet generates explosion sound even if it hits nothing and goes off the screen  
  - [x] Decimal health gets cropped hideously on the screen edge
  - [ ] Pistol reloads instantly first-time, almost instantly most times - Sev: Can not reproduce
  - [x] Charging the railgun triggers a reload while you're still charging. (Charge the railgun, wait for the reload; release, and tap the mouse again -- you can fire two rail shots in short order.)
  - [x] Game over screen not reliably triggered. Game continues to run on player death if NPCs present
- [x] Rescuable NPCs (optional, can die/disappear if not rescued in time)
  - [x] They appear, as escape pods. 
  - [x] They can be "rescued"
  - [x] They provide passive bonuses: shield, more max HP, speed, free random shots at enemies, etc. Show it in the UI as "crew: X" (X = 1, 2, ...).
- [x] Procedural background.
  - [x] Minimum: 2 starry fields, 3 planets (make them big and scale/position randomly), 0-1 nebula
  - [x] Optional: 2 more starfields, 2 more planets, and 1 more nebula
- [ ] Powerups
  - [ ] Health
  - [ ] Faster ammo (temporary)
  - [ ] Move faster (temporary)

# Prototype: In or Out?
- ~~Mini-bosses that appear when rescuable NPCs appear~~

# It's a Wrap
- [x] Game balancing and game design tweaks
  - [x] Orbs need to move faster, they die fast
- [ ] App icon
- [x] Binaries are broken again.
- [ ] Final art
  - [X] Delete (or recreate, if there's time) any planets/suns/etc. that don't fit in with our style? Deleting is easier.  - Sev: Planets re-drawin in pixel-art style (Same shape/colour/etc). Suns and Nebula removed due to difficulty and clashing with new ship colouration.
  - [X] Re-do the ship. Honestly, it looks too big, and at that scale, it aliases really hideously. - Submitted for approval
  - [X] Make a proper escape pod image - Submitted for approval
  - [x] Make an app icon? Using the ship is fine. - 2 versions submitted for approval
  - [X] Make the rocket look nice. Brown, maybe? White looks hideous. - Submitted for approval
  - [X] Unify colour theme - Enemies - Red, Player/NPC - Metal grey, Pickups - Green, misc- varies.
  - [x] Planet size is scalable in code.  - Large planets were a visual distraction.
  - [x] Faces
  - [ ] Enemies
      - [ ] Animated?   - Sev: Some enemy sprites have animated versions, but not yet implemented in code due to time constraints. 
  - [X] Escape pod - Submitted for approval
  - [ ] weapons - Sprites drawn, not yet implemented.
     - [ ] swappable-Rotating sprite tethered to player ship location (Turret)
- [ ] Final testing (with binaries)
- ~~Titlescreen with New Game, Credits, Exit~~

# Discuss and Decide
- ~~Some sort of character progression, like level up (pick: more max health or fire speed up 10% or damage up 25% or something)~~
- ~~Cover objects (10-20 green squares, for example) that absorb bullets, block movement, and eventually get destroyed.~~
- ~~Grid based real-time shooter? like an SRPG like FFA or Disgaea with a single unit played in real time?~~
- ~~Double tab or combo movement keys for dodge or sprint mechanics? Limited stamina?~~
- ~~Nasheeds or some other background audio (wind whipping over the sand?)~~
- ~~World is bigger than what fits on-screen~~

**Comment by severokST** [comment]
Working:
- [x] Object Prototyping: Creating ingame objects from JSON file for arbitrary spawning.
- [x] Object Spawning/Rendering: Cloning object Prototyping into active game & Rendering.
- [x] simple AI handler allowing different behavior instructions to be applied to different types of enemies.
- [x] Periodic function call for updating game + calling AI processing
- [x] Object movement
- [x] Input - Keyboard for movement, mouse for attacking
- [x] Basic Game processing - Update game objects once/frame. For each existing object, call relevent AI, spawn/despawn objects and update positions as needed.
- [x] Collision detection - Enemy||bullet-> Player = die, bullet -> enemy = Despawn
- [x] Basic AI - Simple decision making for various objects based on objects flagged behavior
- [x] Procedual enemy spawning - @ event || time: Spawn(enemy, Random screen boundry position)
- [x] Additional simple weapon types
- [x] Loot spawn on enemy death
- [x] Loot switches player weapon on collision

**Comment by ashes999** [comment]
My TODO list:
- [x] Splash screen with MG logo (fade in, fade out, isolated code)
- [x] Ditto splash screen with DG logo
- [x] Make sure it works on Windows
- [x] Can we generate a one-click binary? [Yes we can](http://gamedev.stackexchange.com/questions/6674/how-can-i-distribute-a-native-executable-for-a-python-program/6677#6677). Do it.
- [x] Binaries include image files in them
- [x] Dynamic reload of `object.json`
- [x] Config class that pulls from JSON, for features

**Comment by ashes999** [comment]
For our Supreme Art Director, @roketfiq:
- [x] GitHub training
- [ ] Plan the overall art direction
- [ ] Experiment with art styles
- [ ] Commit to something
- (Placeholder): backgrounds, player, monsters, walls, enemies, powerups, coins, etc.

**Comment by rehmanabdul13** [comment]
The Super Cool Game Designer (me) Tasks:

- [x] Brainstorm fun features/themes
- [x] Pick a couple that seem reasonable and get feedback
- [ ] Link up with Supreme Art Director @roketfiq to correlate ideas and art direction
- [ ] Demand features and play-test when they're prototyped
- [ ] Approve or revise features
- [ ] Give final set of features because we're out of time

**Comment by severokST** [comment]
I have finished my initial goals.

Awaiting further orders, otherwise I will start getting experimental. 

@rehmanabdul13, Mr Director, direct me!

**Comment by ashes999** [comment]
@severokST I have a few things I would like you to do. I'll help.

I'll ping our Super Cool Game Designer about getting some ideas up today (please go to sleep ...)

**Comment by severokST** [comment]
Can do industrious leader.

Also, we have basic control, graphics, collision, objects and AI.

is it about time we started considering the astetic parts of the engine like sound?

**Comment by ashes999** [comment]
Yes, We're going to start steamrolling over our art and game designer teamies. For now, let's assume those responsibilities too, and at least consult each other.

Yes, we're going to start considering sound, background, etc. 

First discussion: do you want it to be a simpler, everything-in-one-screen game, or should we have a scrolling map? I like the simpler approach myself.

**Comment by ashes999** [comment]
@severokST I updated my comment above with things to do. You can work from the top, down. I'll work from the bottom, up.

**Comment by severokST** [comment]
I neglected to mention in my last post, The player is now restricted from moving offscreen.
The code is not too elegent,  but it works.

For the sake of testing, the player stops movement 100 pixels away from the edge but this will be altered.
